const types = {
    ADD_PRODUCTO:"ADD_PRODUCTO",
    REMOVE_PRODUCTO:"REMOVE_PRODUCTO",
    DECREASE_ONE_PRODUCTO:"DECREASE_ONE_PRODUCTO",
    REMOVE_TOTAL_PRODUCTOS:"REMOVE_TOTAL_PRODUCTOS"
}
export default types;